### ISSUE TITLE
Can't bind to 'start' since it isn't a known property of 'ngx-zxing'.

### ISSUE THREAD

**Issue by msg768** [werthdavid/ngx-zxing#1]
I have followed the steps in your README but I'm getting the following errors:
Any help would be much appreciated!
NodeInvocationException: Template parse errors:
Can't bind to 'start' since it isn't a known property of 'ngx-zxing'.
1. If 'ngx-zxing' is an Angular component and it has 'start' input, then verify that it is part of this module.
2. If 'ngx-zxing' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. (" <div class="modal-body"> 
<ngx-zxing
[ERROR ->][start]="camStarted"
[device]="selectedDevice"
(onCamsFound"): ng:///AppModuleShared/SendComponent.html@132:20
Can't bind to 'device' since it isn't a known property of 'ngx-zxing'.
1. If 'ngx-zxing' is an Angular component and it has 'device' input, then verify that it is part of this module.
2. If 'ngx-zxing' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("
<ngx-zxing
[start]="camStarted"
[ERROR ->][device]="selectedDevice"
(onCamsFound)="displayCameras($event)"
"): ng:///AppModuleShared/SendComponent.html@133:20
'ngx-zxing' is not a known element:
1. If 'ngx-zxing' is an Angular component, then verify that it is part of this module.
2. If 'ngx-zxing' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("
</div>
<div class="modal-body"> 
[ERROR ->]<ngx-zxing
[start]="camStarted"
[device]="selectedDevice"
"): ng:///AppModuleShared/SendComponent.html@131:16
Error: Template parse errors:
Can't bind to 'start' since it isn't a known property of 'ngx-zxing'.
1. If 'ngx-zxing' is an Angular component and it has 'start' input, then verify that it is part of this module.
2. If 'ngx-zxing' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. (" <div class="modal-body"> 
<ngx-zxing
[ERROR ->][start]="camStarted"
[device]="selectedDevice"
(onCamsFound"): ng:///AppModuleShared/SendComponent.html@132:20
Can't bind to 'device' since it isn't a known property of 'ngx-zxing'.
1. If 'ngx-zxing' is an Angular component and it has 'device' input, then verify that it is part of this module.
2. If 'ngx-zxing' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("
<ngx-zxing
[start]="camStarted"
[ERROR ->][device]="selectedDevice"
(onCamsFound)="displayCameras($event)"
"): ng:///AppModuleShared/SendComponent.html@133:20
'ngx-zxing' is not a known element:
1. If 'ngx-zxing' is an Angular component, then verify that it is part of this module.
2. If 'ngx-zxing' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("
</div>
<div class="modal-body"> 
[ERROR ->]<ngx-zxing
[start]="camStarted"
[device]="selectedDevice"
"): ng:///AppModuleShared/SendComponent.html@131:16
at syntaxError (c:\Users\Markus\WebWallet\webwallet\ClientApp\dist\vendor.js:26832:34)
at TemplateParser.module.exports.TemplateParser.parse (c:\Users\Markus\WebWallet\webwallet\ClientApp\dist\vendor.js:37944:19)
at JitCompiler.module.exports.JitCompiler._compileTemplate (c:\Users\Markus\WebWallet\webwallet\ClientApp\dist\vendor.js:51989:39)
at c:\Users\Markus\WebWallet\webwallet\ClientApp\dist\vendor.js:51909:62
at Set.forEach (<anonymous>)
at JitCompiler.module.exports.JitCompiler._compileComponents (c:\Users\Markus\WebWallet\webwallet\ClientApp\dist\vendor.js:51909:19)
at c:\Users\Markus\WebWallet\webwallet\ClientApp\dist\vendor.js:51796:19
at Object.then (c:\Users\Markus\WebWallet\webwallet\ClientApp\dist\vendor.js:26822:92)
at JitCompiler.module.exports.JitCompiler._compileModuleAndComponents (c:\Users\Markus\WebWallet\webwallet\ClientApp\dist\vendor.js:51795:26)
at JitCompiler.module.exports.JitCompiler.compileModuleAsync (c:\Users\Markus\WebWallet\webwallet\ClientApp\dist\vendor.js:51724:37)

**Comment by msg768** [comment]
I think I found out the problem today. I have an extra < in my code :/

**Comment by werthdavid** [comment]
Hey,

I'm currently updating the README...
I think importing the FormsModule should solve the problem:

import {FormsModule} from "@angular/forms";

and

@NgModule({
  imports: [ 
    BrowserModule,
    **FormsModule**,
    **NgxZxingModule.forRoot()**
  ],
  declarations: [ App ],
  bootstrap: [ App ]
})

I'll post a working Plunkr soon.

**Comment by msg768** [comment]
Thanks! I ended up using instascan in an iframe in my angular project and it's working! :)

**Comment by werthdavid** [comment]
Nice ;-)
I made this b/c I was not so happy with instascan...

**Comment by msg768** [comment]
Fair enough :P
