### ISSUE TITLE
don't work with barcode

### ISSUE THREAD

**Issue by flvmoreno** [werthdavid/ngx-zxing#14]
the component works fine with qrcode, but not with barcode. i'm trying to implement a both reader with next code: 

`<ngx-zxing
 [start]="camStarted"
 [device]="selectedDevice"
 (onCamsFound)="displayCameras($event)"
 (onScan)="handleQrCodeResult($event)"
></ngx-zxing>`

**Comment by werthdavid** [comment]
Correct, that's a limitation of the [zxing-typescript](https://github.com/aleris/zxing-typescript) library that is used.
