### ISSUE TITLE
Publish npm package under scope (refactoring needed)

### ISSUE THREAD

**Issue by odahcam** [werthdavid/ngx-zxing#23]
I think we can do this for v1.0.0, a major release indicating that some things will change completely.

We also gotta decide what name use for the scanner component, maybe `NgxScannerComponent` and `NgxScannerModule`? (maybe it's too generic)

 - [x] Publish package.
 - [x] Rename classes.
 - [ ] Release G.A. version.

**Comment by odahcam** [comment]
First dev version published named as `@zxing/ngx-scanner`. Component not renamed yet, it will be named as `ZXingScannerModule`

**Comment by werthdavid** [comment]
I would say so. Makes it obvious that it is an angular component

**Comment by odahcam** [comment]
Do you need to say that this is a Angular component when you use inside Angular the package is already published under the `ngx-` preffix?

**Comment by werthdavid** [comment]
Well... Good point! :grin: Let's go without the prefix then

**Comment by odahcam** [comment]
I finished the refactoring (I think..).

Can ya do some review to the code? I'm really anxious about finishing this.

**Comment by werthdavid** [comment]
Will do! 👍🏻

**Comment by werthdavid** [comment]
Looks good, lets go 😁

**Comment by werthdavid** [comment]
I'm currently working on a Plunkr example which can then be exported and added to the docs-folder so a demo can be accessed via github.io
The docs-folder is the only folder I found the old ngx-zxing name so I think were ready for an initial release now
