### ISSUE TITLE
Default throttling should be set

### ISSUE THREAD

**Issue by csutorasr** [werthdavid/ngx-zxing#24]
**Why change an existing behavior?**
The default throttling is now 1500ms. It may differ for applications.

**Expected behavior**
There should be an providable config object also for the configurations maybe added later.

**Comment by odahcam** [comment]
I'm working on it and it seems a little odd, because throttling needs to be set throught the qr reader class instantiation. Things can get a little unperformant if I bind this behavior to an `@Input` property. We gotta discuss some ideas on how to implement this.

**Comment by csutorasr** [comment]
As I told you it can be injected. I will add the  link from the docs later.

**Comment by odahcam** [comment]
If you know how to do, add your snippet here and I will properly add to the project, or make a PR. 😁

**Comment by csutorasr** [comment]
They are called injection tokens. Here is the docs: [https://angular.io/guide/dependency-injection#dependency-injection-tokens](https://angular.io/guide/dependency-injection#dependency-injection-tokens)

If I have time I will make the changes.

**Comment by werthdavid** [comment]
Can we close that now?
