### ISSUE TITLE
Camera not opening in Android Web View app 

### ISSUE THREAD

**Issue by praveenrengarajan** [werthdavid/ngx-zxing#29]
I am trying same web application in Android WebView app, even I gave camera permission, it's not showing any camera list and not opening the camera. Is it any permission problem, or have to do some other setup?

**Comment by werthdavid** [comment]
https://stackoverflow.com/questions/38917751/webview-webrtc-not-working

Does that help by any chance?

**Comment by praveenrengarajan** [comment]
@werthdavid  working thanks

**Comment by odahcam** [comment]
You're welcome.
