### ISSUE TITLE
Webcam do not stop when component is destroyed

### ISSUE THREAD

**Issue by Timothee-Retailleau** [werthdavid/ngx-zxing#3]

**Comment by werthdavid** [comment]
Good point, will check on that!

**Comment by ami-nsi** [comment]
Is this issue really closed?

**Comment by odahcam** [comment]
Yep, do you think this should be reopened?

**Comment by ami-nsi** [comment]
No it's fixed.
Apparently I had this issue when using some PrimeNg components.
It's probably my bad, sorry for trouble.

**Comment by odahcam** [comment]
No problem, feel free to file a new issue if you need.
