### ISSUE TITLE
Doesn't scan and display the result.

### ISSUE THREAD

**Issue by lbrep** [werthdavid/ngx-zxing#30]
Although It correctly detects the camera, the `ngx-zing.umd.js` makes attempts which is logged in the console, but can't scan and display results.
Even on the stackblitz example given, I do not see any results. While the plunker example scans it immediately. 
Any help is appreciated.

**Comment by odahcam** [comment]
Please, provide technology, device, browser, etc. you're using.

**Comment by odahcam** [comment]
Closing because it has not the required info.
