### ISSUE TITLE
Change detection performance

### ISSUE THREAD

**Issue by werthdavid** [werthdavid/ngx-zxing#33]
Set the component to changeDetection: ChangeDetectionStrategy.OnPush to increase performance

**Comment by odahcam** [comment]
I could not understand whats exactly is that feature, maybe we should put it in v1.1.0 milestone else we will never finish v1.0.0. 😆 

Also, let's keep an eye on performance and try to keep it fast as is, it's an awesome and killer feature against concurrents. 😉

**Comment by werthdavid** [comment]
Good point that's indeed something for 1.1
