### ISSUE TITLE
ngDevMode redeclare

### ISSUE THREAD

**Issue by csutorasr** [werthdavid/ngx-zxing#34]
Error given by angular-cli.

```
ERROR in node_modules/@angular/core/src/render3/ng_dev_mode.d.ts(9,11): error TS2451: Cannot redeclare block-scoped variable 'ngDevMode'.
node_modules/@zxing/ngx-scanner/node_modules/@angular/core/src/render3/ng_dev_mode.d.ts(9,11): error TS2451: Cannot redeclare block-scoped variable 'ngDevMode'.
```

The problem probably is the Angular is also installed in the `node_modules` of ngx-scanner module, and they are colliding.

Version: 1.0.0-dev.759282

On windows machine removing the `node_modules/@zxing/ngx-scanner/node_modules` folder solved the problem.
Under linux on CircleCI there was no problem.

**Comment by odahcam** [comment]
Could you update to the latest version and test again?

**Comment by csutorasr** [comment]
I close this, as it has worked with the latest version.

**Comment by odahcam** [comment]
Nice to hear that! 🎉
