### ISSUE TITLE
Remove log output

### ISSUE THREAD

**Issue by werthdavid** [werthdavid/ngx-zxing#36]
I'd suggest that we remove the console.log and console.warn output or at least replace it with console.debug (`browser-code-reader.ts`)

**Comment by csutorasr** [comment]
Are those needed?

I think all of them could be removed from builds, as they are only used in development of the library. If the library works, no one will use them. If someone would like to debug the library they will pull the repo and see the console.

**Comment by odahcam** [comment]
Please, note that I'm publishing under a `v0.0.0-**dev**.<hash>` tag, I intend to remove these logs at the final version as well. 😄

**Comment by odahcam** [comment]
Done.
