### ISSUE TITLE
Not scanning all Types of QR Codes

### ISSUE THREAD

**Issue by praveenrengarajan** [werthdavid/ngx-zxing#37]
I thought this library will work for all types of QR code, but its not reading some QR code.
Not Scanning QR:
![notworkingqr](https://user-images.githubusercontent.com/2884636/36713086-d7000382-1bb1-11e8-89ed-7b2249ebbd1f.PNG) 
Working QR:
![working-qr](https://user-images.githubusercontent.com/2884636/36713087-d72e9ada-1bb1-11e8-92bb-c914e76a57cc.PNG)

**Comment by werthdavid** [comment]
Code works with [zxing-online](https://zxing.org/w/decode.jspx)

**Comment by werthdavid** [comment]
That exact code works with latest develop (see attached file).
I took your code and added a [quiet-zone](https://qrworld.wordpress.com/2011/08/09/the-quiet-zone/) which increases readability. Do you have the chance to influence the generation of the codes?

**Comment by praveenrengarajan** [comment]
"ngx-zxing": "^0.3.4" ,
I had generated again the qr code again in 4x mode, but still its not reading.
what is the latest version of `ngx-zxing` ?

**Comment by werthdavid** [comment]
I retested it with the Plunkr from the README (uses 0.3.4) on my iPhone. Worked there as well. I realized there is a small grey border around your code in the first comment, maybe this causes problems.

0.3.4 is the most recent version at the moment but we're about to release 1.0.0 soon!

@odahcam what you think about publishing a dev-version to npm?

**Comment by odahcam** [comment]
Well, I'm already publishing lots of dev versions 😆 

I recomend the `1.0.0-dev.a5265f` which I'm using in my app. You can add it to your `package.json`:

```javascript
{ 
    //...
        "@zxing/ngx-scanner": "^1.0.0-dev.a5265f",
    // ...
}
```

Or install via yarn/npm: `npm i @zxing/ngx-scanner@1.0.0-dev.a5265f --save`

You can also play with the latest version at: https://stackblitz.com/edit/zxing-ngx-scanner

Cheers.

**Comment by werthdavid** [comment]
@praveenrengarajan does the issue still exist with 1.0.0-dev?

**Comment by praveenrengarajan** [comment]
@werthdavid  facing another problem while installing -dev. 
`
sharp@0.18.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sharp@0.18.4 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
`
working on it

**Comment by odahcam** [comment]
This is a problem with your environment, try to install: 
```bash
npm install --global --production windows-build-tools
```
...and try again.

**Comment by praveenrengarajan** [comment]
@odahcam yep, that was the proxy issue, it didn't allow me to install sharp. 
`Cannot read property 'camerasFound' of undefined`
import { NgxZxingComponent } from '@zxing/ngx-scanner'; in component
and in module import { NgxZxingModule } from 'ngx-zxing';

component OnInit getting error, default camera getting activated for milliseconds and closed.

**Comment by odahcam** [comment]
You should import `from '@zxing/ngx-scanner'` after the update.

I'm closing the issue because the main topic was already clarified.
