### ISSUE TITLE
Option for disabling autofocus

### ISSUE THREAD

**Issue by werthdavid** [werthdavid/ngx-zxing#40]
Disabling autofocus can potentially increase performance.
Add an option to disable it.

**Comment by odahcam** [comment]
So, that attribute didn't work?

**Comment by lawrencetaur** [comment]
I can confirm that this works.

**Comment by werthdavid** [comment]
Just reopened it to rename the property as suggested in the comment of the commit

**Comment by werthdavid** [comment]
@odahcam renamed the property so the issue will be closed

**Comment by odahcam** [comment]
Thanks, I forgot to report that.
