### ISSUE TITLE
Are 1D barcodes supported?

### ISSUE THREAD

**Issue by pier2013** [werthdavid/ngx-zxing#41]
Hi,

first of all thank your for your efforts in making this port working on angular. Your library works like a charm for QR, but I haven't managed to find a way to scan 1D barcodes. I didn't find any clue about that.

I am using angular 5.2.8 and `@zxing/ngx-scanner` 1.0.0-dev.ec70451. Windows 10 and Android L on Nexus 5x.

Thank you

**Comment by werthdavid** [comment]
Hey,
Unfortunately it only supports QR at this time.
The component relays on [zxing-typescript](https://github.com/aleris/zxing-typescript) (which we forked) under the hood but 1D codes are not implemented there (yet)

**Comment by pier2013** [comment]
Thank you

**Comment by theomarshanti** [comment]
Are there any plans to scan 1D barcodes as well?

**Comment by odahcam** [comment]
1D barcodes are already supported at this time, hehe. 

Take a look on the supported formats: https://github.com/zxing-js/library#supported-formats

**Comment by theomarshanti** [comment]
Thanks! Working fine now :)
