### ISSUE TITLE
AOT Production Build: Failed

### ISSUE THREAD

**Issue by praveenrengarajan** [werthdavid/ngx-zxing#43]
`ERROR in @zxing\ngx-scanner\zxing-ngx-scanner.ts(9,2): Error during template compile of 'NgxZxingModule'
  Function calls are not supported in decorators but 'ɵmakeDecorator' was called in 'NgModule'
    'NgModule' calls 'ɵmakeDecorator'`

Package.json:  `"@zxing/ngx-scanner": "^1.0.0-dev.a5265f"`

Getting above error, while we build project in production mode (aot=true)

**Comment by odahcam** [comment]
Angular version?

**Comment by praveenrengarajan** [comment]
Angular CLI: 1.6.3
Node: 6.11.0
OS: win32 x64
Angular: 5.1.3

**Comment by werthdavid** [comment]
Please update the library: `@zxing/ngx-scanner": "^1.0.0-dev.1.0.0-dev.ec70451` is the latest version, production build with `ng build --target=production --environment=prod` works fine for me

**Comment by praveenrengarajan** [comment]
Still facing same problem, upgraded to ec70451
![image](https://user-images.githubusercontent.com/2884636/37323408-a3d34cbe-26a9-11e8-95fe-144a84fc1f82.png)

package.json
![image](https://user-images.githubusercontent.com/2884636/37323427-d06a1050-26a9-11e8-801e-173a9c829c20.png)

**Comment by werthdavid** [comment]
- did you use yarn or npm?
- any linked dependencies?
- can you maybe update CLI to 1.7.x just to be sure..?
- anything special in tsconfig.json?
- you probably saw [this](https://github.com/angular/angular-cli/issues/4647#issuecomment-305967234) already..?

**Comment by praveenrengarajan** [comment]
- using npm
- no dependencies in that particular module
- tsconfig

{
  "compileOnSave": false,
  "compilerOptions": {
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "target": "es5",
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es2017",
      "dom"
    ]
  }
}
**will try update CLI to 1.7x**

**Comment by werthdavid** [comment]
I created a new Angular Project with CLI 1.7.3 that gives me this package.json
[package.json.txt](https://github.com/werthdavid/ngx-zxing/files/1806531/package.json.txt)
running `npm run build` works fine.. poking in the dark here 😕

**Comment by praveenrengarajan** [comment]
https://github.com/angular/angular-cli/issues/3854#issuecomment-274344771 this one helped.

**Comment by werthdavid** [comment]
Awesome! 🎉
