### ISSUE TITLE
onCamsFound issue with mobile device

### ISSUE THREAD

**Issue by Timothee-Retailleau** [werthdavid/ngx-zxing#5]
(onCamsFound) do not work with mobile device.

The function do not retrieve any camera.

Scanner is still working but using the first camera referenced in the device.

**Comment by werthdavid** [comment]
Android or iOS?
(Mobile-)Browsers usually block the camera access if your page is not delivered via HTTPS! And on iOS it only works with native Safari.

**Comment by Timothee-Retailleau** [comment]
Android.
I'm using https so it's not related to this. I'll try to explore a little bit more in few days.

**Comment by werthdavid** [comment]
I just tested it with an emulated Android device (API Level 25; 7.1.1, x86) and there it works fine with Chrome... What Browser and OS version are you using? Are you sure the Browser has the permission to access the camera?

**Comment by mattgek** [comment]
Will there be a fix for ofther browsers on IOS beside native Safari?

**Comment by werthdavid** [comment]
Nobody knows... the issue with iOS is not related to this library but WebKit/WKWebView. Let's hope Apple will support WebRTC at some point in the future for other Browsers. 

for some further reading see (this blog entry)[https://bloggeek.me/webrtc-ios-support/]

**Comment by mattgek** [comment]
@werthdavid Ok thanks for the quick response.

**Comment by odahcam** [comment]
I think this is related to #16.

It seems very outdated and hard to track, so I'm closing. Feel free to open a new issue if I'm wrong, regards.
