### ISSUE TITLE
decode triggered although stopped

### ISSUE THREAD

**Issue by ntswor** [werthdavid/ngx-zxing#7]
It seems that there is a problem when stopping the camera. I'm always getting this exception:
```
ERROR TypeError: Cannot read property 'naturalWidth' of undefined
    at BrowserQRCodeReaderExt.BrowserCodeReaderExt.prepareCaptureCanvas (ngx-zxing.umd.js:8022)
    at BrowserQRCodeReaderExt.BrowserCodeReaderExt.decode (ngx-zxing.umd.js:7980)
```

As far as I've seen the decodeWithDelay is called again when the callback of the result returns. There is just a check if the decode should be done once (which is false per default). Therefore a new timer will start and it tries to get the input once again:

```
callbackFn(result);
if (!once) {
	setTimeout(function () { return _this.decodeWithDelay(callbackFn); }, this.timeBetweenScansMillis);
}
```

Solution may be to check if the process is already stopped and if so, the decoding is not called again.

**Comment by werthdavid** [comment]
Thanks for the research, will address this issue in the next release!

**Comment by ntswor** [comment]
Thx for your fast response. I had a look at the commit and tested it locally. It's not solving the problem I mentioned.

The problem I'm referring to happens in the BrowserCodeReaderExt class. I will try to describe my use case a little bit in more detail:

- I'm adding the component and starting the camera (by setting the start input to true)
- As soon as I'm getting a response from the scan I'm stopping the camera (again by changing the start input to false - I even tried to call the stop method directly)
- the camera is stopped correctly (BrowserCodeReaderExt stop() is called)
- the stream is closed
- but now the callbackFn of the BrowserCodeReaderExt decode function returns a value and the check is done if the scan should only be done once 
- if false (and it is false all the time) a new timeout is set and the decode is called again which leads to the mentioned error

A solution might be to not only check if the decode should be done once but also to check if the stream is still set:

```
if (!once && undefined !== this.stream) {
	setTimeout(function () { return _this.decodeWithDelay(callbackFn); }, this.timeBetweenScansMillis);
}
```

I have created a pull request (my first one on github) - so if you can have a look or give me feedback, I would appreciate it.

**Comment by werthdavid** [comment]
Thanks for the detailed analysis and the PR! Looks good to me, I merged it. Thanks! BTW: my first angular component and also my first active project on github as well :wink:
